language: rust

branches:
  only:
    - staging
    - trying

matrix:
  include:
    - rust: beta
      script:
        - cargo run --package tasks -- verify
        - cargo test
        - cargo run --example api-walkthrough
