[package]
name = "tom"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[workspace]
members = ["tasks"]

[dependencies]
itertools = "0.7"
lazy_static = "1"
m_lexer = "0.0.4"
parse_tree = "0.0.6"
regex = "1"
typed-arena = "1.3"
typed_index_derive = "0.1.4"
uncover = "0.1"

[dev-dependencies]
testutils = { path = "./tests/testutils" }
