[package]
name = "tom"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[dependencies]
lalrpop-util = "0.15"
regex = "1"
typed-arena = "1.3"

[build-dependencies]
heck = "0.1.0"
lalrpop = "0.15"

[dev-dependencies]
testutils = { path = "./tests/testutils" }
