[package]
name = "tom_wasm"
version = "0.0.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[workspace]

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = false
lto = true
panic = 'abort'
opt-level = 's'

[dependencies]
wasm-bindgen = "0.2.11"
tom = { path = "../" }
